# Lead Engineer Note: aiosmtplib is the async-native SMTP client. Using the
# standard smtplib (synchronous) inside an async FastAPI endpoint would BLOCK
# the entire event loop during the email send — potentially freezing all other
# requests. aiosmtplib sends without blocking.

import aiosmtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv

load_dotenv()

SMTP_HOST     = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT     = int(os.getenv("SMTP_PORT", "587"))
SENDER_EMAIL  = os.getenv("SENDER_EMAIL")
SENDER_PASS   = os.getenv("SENDER_PASSWORD")


def _build_html_email(recipient: str, ai_brief: str, stats: dict) -> MIMEMultipart:
    """
    Builds a polished HTML email. Returns a MIMEMultipart message object.
    Lead Engineer Note: Sending HTML + plain-text (multipart/alternative) ensures
    the email renders in all clients — Outlook, Gmail, Apple Mail, mobile.
    """
    msg = MIMEMultipart("alternative")
    msg["Subject"] = "📊 Q1 2026 Sales Intelligence Brief"
    msg["From"]    = f"Sales Insight Automator <{SENDER_EMAIL}>"
    msg["To"]      = recipient

    # Plain text fallback
    plain = f"""Q1 2026 Sales Intelligence Brief

{ai_brief}

---
Key Metrics:
- Total Revenue:    ${stats.get('total_revenue', 0):,.2f}
- Total Units Sold: {stats.get('total_units_sold', 0):,}
- Top Category:     {stats.get('top_category', 'N/A')} (${stats.get('top_category_revenue', 0):,.2f})

Generated by Sales Insight Automator
"""

    # Format AI bullets as HTML list items
    bullet_lines = [
        line.strip() for line in ai_brief.split("\n") if line.strip()
    ]
    bullets_html = "\n".join(
        f'<li style="margin-bottom:12px; line-height:1.6;">{line.lstrip("•- ")}</li>'
        for line in bullet_lines
    )

    html = f"""
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:'Georgia',serif;">
  <table width="100%" cellpadding="0" cellspacing="0">
    <tr><td align="center" style="padding:40px 20px;">
      <table width="600" cellpadding="0" cellspacing="0"
             style="background:#ffffff;border-radius:8px;overflow:hidden;
                    box-shadow:0 2px 12px rgba(0,0,0,0.08);">

        <!-- Header -->
        <tr><td style="background:#0f172a;padding:32px 40px;">
          <p style="margin:0;color:#94a3b8;font-size:12px;letter-spacing:3px;
                    text-transform:uppercase;">Sales Intelligence</p>
          <h1 style="margin:8px 0 0;color:#f8fafc;font-size:26px;font-weight:600;">
            Q1 2026 Executive Brief
          </h1>
        </td></tr>

        <!-- Stats Bar -->
        <tr><td style="background:#1e293b;padding:20px 40px;">
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr>
              <td align="center" style="border-right:1px solid #334155;padding:0 16px 0 0;">
                <p style="margin:0;color:#64748b;font-size:11px;
                          text-transform:uppercase;letter-spacing:2px;">Revenue</p>
                <p style="margin:4px 0 0;color:#34d399;font-size:20px;font-weight:700;">
                  ${stats.get('total_revenue', 0):,.0f}
                </p>
              </td>
              <td align="center" style="border-right:1px solid #334155;padding:0 16px;">
                <p style="margin:0;color:#64748b;font-size:11px;
                          text-transform:uppercase;letter-spacing:2px;">Units Sold</p>
                <p style="margin:4px 0 0;color:#f8fafc;font-size:20px;font-weight:700;">
                  {stats.get('total_units_sold', 0):,}
                </p>
              </td>
              <td align="center" style="padding:0 0 0 16px;">
                <p style="margin:0;color:#64748b;font-size:11px;
                          text-transform:uppercase;letter-spacing:2px;">Top Category</p>
                <p style="margin:4px 0 0;color:#f8fafc;font-size:20px;font-weight:700;">
                  {stats.get('top_category', 'N/A')}
                </p>
              </td>
            </tr>
          </table>
        </td></tr>

        <!-- AI Brief -->
        <tr><td style="padding:36px 40px;">
          <p style="margin:0 0 16px;color:#64748b;font-size:11px;
                    text-transform:uppercase;letter-spacing:2px;">
            AI-Generated Analysis
          </p>
          <ul style="margin:0;padding-left:20px;color:#1e293b;font-size:15px;">
            {bullets_html}
          </ul>
        </td></tr>

        <!-- Footer -->
        <tr><td style="background:#f8fafc;padding:20px 40px;
                        border-top:1px solid #e2e8f0;">
          <p style="margin:0;color:#94a3b8;font-size:12px;">
            Generated by <strong>Sales Insight Automator</strong> · Powered by Gemini AI
          </p>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>
"""

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))
    return msg


async def send_report_email(recipient: str, ai_brief: str, stats: dict) -> None:
    """
    Sends the AI-generated report to the recipient via SMTP.

    Raises:
        RuntimeError: If SMTP credentials are missing or the send fails.
    """
    if not SENDER_EMAIL or not SENDER_PASS:
        raise RuntimeError(
            "SENDER_EMAIL or SENDER_PASSWORD is not set in .env. "
            "Email delivery is disabled."
        )

    msg = _build_html_email(recipient, ai_brief, stats)

    try:
        await aiosmtplib.send(
            msg,
            hostname=SMTP_HOST,
            port=SMTP_PORT,
            username=SENDER_EMAIL,
            password=SENDER_PASS,
            start_tls=True,
        )
    except aiosmtplib.SMTPException as e:
        raise RuntimeError(f"Email delivery failed: {e}")
